### ISSUE TITLE
Formatos de salida

### ISSUE THREAD

**Issue by nachopro** [trifulca/buchonip#1]
Hoy en día responde un HTML con la IP dentro de un `<pre>`
Creo que habría que simplificarlo o al menos implementar formatos de salida predefinido:

```
/?json` -> {'ip': 'x.x.x.x'}
/?txt  -> 'x.x.x.x'
```

¿Opiniones @hugoruscitti @iglosiggio ?

**Comment by hugoruscitti** [comment]
Si, a full. Lo único que me parece medio raro es el parámetro get. ¿Si usamos un header para esto https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values?

**Comment by nachopro** [comment]
Mmm... Mejor `/json` y `/txt`, es más simple de hacer un curl o wget o bla bla...

Debatamos!!!

**Comment by hugoruscitti** [comment]
Si lo pones en un readme.md compro.

**Comment by nachopro** [comment]
@hugoruscitti de hecho creo que el `/` debería darte la IP humanamente leible y links a `/txt` y `/json`.
Además de un pequeño ad (?)

Tamos proveyendo alto servicio, maestro!
