### ISSUE TITLE
Proceso de Deploy

### ISSUE THREAD

**Issue by nachopro** [trifulca/buchonip#10]
Hay que definir cómo lo vamos a poner en producción.

- Subir binario al server
- Reiniciar el servicio con `supervisorctl`

¿Quién hace el binario?
¿Quién sube y reinicia el servicio?

**Comment by nachopro** [comment]
@hugoruscitti la otra es usar esto: https://aws.amazon.com/es/elasticbeanstalk/

Creás un servicio, le asignás un DNS y los tipos ejecutan tu binario.
Yo hasta 100 pe por mes le metería (?)

**Comment by hugoruscitti** [comment]
Ahí hice una prueba sencilla, puse un comando "make deploy" para compilar local (cross compilado) y re-deployar por ssh.

Creo que una mejora sería configurar circle.ci para que ejecute ese comando "make deploy" cuando se detecta un tag nuevo. Osea, en lugar de ejecutar "make deploy" local, podría ser circle.ci quién haga los deploys, siempre y cuando encuentre un tag nuevo.

Acá hay un ejemplo de eso: https://github.com/pilas-engine/pilas-engine/blob/master/.circleci/config.yml#L58

**Comment by nachopro** [comment]
Lo del Make me parece bien!

`$ GOOS=linux GOARCH=386 go build -o buchonip-$(echo $GOOS)-$(echo $GOARCH) buchonip.go`
`$ GOOS=linux GOARCH=amd64 go build -o buchonip-$(echo $GOOS)-$(echo $GOARCH) buchonip.go`

;)

**Comment by nachopro** [comment]
PD: los pipelines de bitbucket permiten hacer builds de Go!!!
¿acá con github cómo se hace? Microsó Basura!

**Comment by nachopro** [comment]
@hugoruscitti faltó configurar la variable de entorno GOOGLE_ANALYTICS_ID
Entiendo que va en el server y no en el CI ni otro script, pero OJOta!

**Comment by hugoruscitti** [comment]
Liisttooo, ahí quedó funcionando. Había que agregarlo en la configuración de systemd
