### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by nachopro** [trifulca/buchonip#3]
![2l7ukr](https://user-images.githubusercontent.com/260549/47650428-ff36f280-db5e-11e8-8101-71ed3ca92ee1.jpg)

@hugoruscitti

**Comment by hugoruscitti** [comment]
Agrego unos links al respecto, y sigo investigando....


- https://medium.com/@pierreprinetti/test-driven-development-in-go-baeab5adb468
- https://github.com/nathany/looper

**Comment by nachopro** [comment]
muy bueno @hugoruscitti pero no vi nada hasta el momento!

**Comment by hugoruscitti** [comment]
Boca está jugando!!! Dame 10’ y te escribo unos test que se te va a caer la
mandíbula al piso!!
